version: '3.8'

services:
  app:
    build: .
    container_name: laravel_app
    volumes:
      - ./:/var/www/html
    ports:
      - 8888:80
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=base64:UBGy5y2KV/LPlhLE0PYH5AvHhK8EkFkUmJCZKf0BwEY=
      - APP_URL=http://localhost
      - DB_CONNECTION=mysql
      - DB_HOST=127.0.0.1
      - DB_PORT=3333
      - DB_DATABASE=LaravelAuth
      - DB_USERNAME=root
      - DB_PASSWORD=secret
    depends_on:
      - db
    networks:
      - app_network
    restart: unless-stopped

  db:
    image: mariadb:latest
    container_name: maria_db
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=LaravelAuth
      - MYSQL_USER=root
      - MYSQL_PASSWORD=secret
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 3333:3306
    networks:
      - app_network
    restart: unless-stopped

volumes:
  db_data:

networks:
  app_network:
    driver: bridge
